[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Explicit remappings for OpenZeppelin contracts
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
